apiVersion: v2
name: soc-platform
description: Unified Open-Source SOC Platform Helm Chart
type: application
version: 1.0.0
appVersion: "1.0.0"
maintainers:
  - name: Boni Yeamin
    url: https://github.com/boniyeamincse
keywords:
  - soc
  - siem
  - wazuh
  - thehive
  - keycloak
  - security
dependencies:
  - name: postgresql
    version: "15.x"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
